from typing import Optional
from sqlmodel import Field, SQLModel


class Snapshot(SQLModel, table=True):
    # id is optional because it generated by the db, not this code
    id: Optional[int] = Field(default=None, primary_key=True)
    time: int = Field(index=True)  # creates an index for Snapshot.time entries for easier
    data: int

